# Mirrors GitHub's Pages builder so `bundle exec jekyll serve` shows exactly
# what gets deployed. Local preview:
#
#   cd site && bundle install
#   bundle exec jekyll serve    # http://localhost:4000/pwt/
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "webrick"
